@Application_HostAddress = http://localhost:5000

### Get category list
GET {{Application_HostAddress}}/api/categories?page=1&pageSize=3&orderBy=Name&order=asc
Accept: application/json

### Get category
GET {{Application_HostAddress}}/api/categories/9
Accept: application/json

### Delete category
DELETE {{Application_HostAddress}}/api/categories/2
Accept: application/json

### Add Category
POST {{Application_HostAddress}}/api/categories
Accept: application/json
Content-Type: application/json

{
    "Name": "Ostanato7",
    "Type": 1,
    "IconFk": 1
}

### Update Category
PUT  {{Application_HostAddress}}/api/categories/12
Accept: application/json
Content-Type: application/json

{
    "Name": "Salary Edited",
    "Type": 1,
    "IconFk": 1
}

### Get Icons List
GET  {{Application_HostAddress}}/api/categories/icons
Accept: application/json